### ISSUE TITLE
peer not able to join channel

### ISSUE THREAD

**Issue by ayshvm** [vanitas92/fabric-external-chaincodes#10]
Repo is very helpful. Thanks
Was able to set all things up on EKS and ran below commands on org1-cli container

peer channel create -o orderer0:7050 -c mychannel -f ./scripts/channel-artifacts/channel.tx --tls true --cafile $ORDERER_CA
which created mychannel.block

On running 
peer channel fetch 0 mychannel.block -c mychannel -o orderer0:7050 --tls --cafile $ORDERER_CA

**ERROR**:
2021-02-13 17:26:00.882 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: proposal failed (err: rpc error: code = Unknown desc = error validating proposal: access denied: channel [] creator org [org1MSP])

Appreciate your help on above error.

**Comment by vanitas92** [comment]
Hi @vermayush ,

That is weird. Please make sure that you are pointing the correct peer with its appropriate certificates. The access denied seems like you are pointing the command to the peer of org2 with the certs or id of org1.

**Comment by ayshvm** [comment]
I was missing CORE_PEER_MSPCONFIGPATH in the env in the yaml files for the deployment of peers.

adding this allowed me to successfully join the channel.
- name: CORE_PEER_MSPCONFIGPATH
              value: <basepath>/peerOrganizations/org1/peers/peer0-org1/msp
              
it is not part of repo. maybe you can do a new setup and validate it .

**Comment by vanitas92** [comment]
By default, the msp has to be on this path inside the peer container: `/etc/hyperledger/fabric/msp`, if you are mapping the msp file to somewhere else, then you would need this env var setup for sure. I have build many networks and I have not needed to set this env var.
