### ISSUE TITLE
Deploying HLF 2.2

### ISSUE THREAD

**Issue by nkaramolegos** [vanitas92/fabric-external-chaincodes#16]
Hello, I have a question. Can I use this repository to deploy my HLF 2.2 network and let k8s make the management? For example the restore of the pods if something fails? Also, can I use this project to maintain my HLF network after deploying? For example, to extend the number of channels, or orgs, or peers in an easy way?

**Comment by vanitas92** [comment]
Hi @nkaramolegos ,

Yes, you can use this project for setting up Hyperledger Fabric in K8s cluster and let k8s do the basic operations it supports. You can also use this project as a template for extending the network. A couple of warnings though, this repo is meant to try, test and develop a feature of Hyperledger Fabric, so this setup is not suitable for a production setup. Also, the version pinned now is 2.3.1, so you will need to use the version 2.2 if you still want to use the LTS version.

Hope it helps!

**Comment by nkaramolegos** [comment]
Thank you. What do you mean is not t for production? What should I change?

**Comment by nkaramolegos** [comment]
My scenario is to create a or multiple k8s clusters. Each time a new user is register to an IoT platform I would like to deploy a specific (pre-defined) BC network to the cluster (the cluster can be same for each user or different - I have to decide-). The pre-defined network will consist of 3 orgs with 2 peers each one which will be connected to the same channel. Can I do all this process using your repository? For example if a new user register I will use kubectl commands (i.e a bash scripts) to deploy the new network?

**Comment by vanitas92** [comment]
Hi @nkaramolegos ,

I just simply state that this repo is just a reference to get the external chaincode feature working in a test or dev environment and anybody can use it for this purpose. That being said, I do not recommend this to use for production usecase as it is not ready to handle all the requirements needed to set this up for production, like backup data, high-availability, etc.

You have to evaluate and see if this is something useful for you as a start for your project and from there work on the modifications you need to make your usecase working. I cannot assess wheter this is best for you and won't do it.

Thank you!

**Comment by nkaramolegos** [comment]
Thank you very much for your advice. For the state database I can use LevelDB or CouchDB as usual. Correct?
