### ISSUE TITLE
Error during deployment of orderers

### ISSUE THREAD

**Issue by nkaramolegos** [vanitas92/fabric-external-chaincodes#17]
The creation is fine but when I type kubectl get pods -n hyperledger, I get:
orderer0-5c4b9dc9dd-f8jcr   0/1     CrashLoopBackOff   11         32m
orderer1-6995df9695-vtmhc   0/1     CrashLoopBackOff   11         32m
orderer2-84c77cc48d-wcw7c   0/1     CrashLoopBackOff   11         32m

**Comment by nkaramolegos** [comment]
Some logs might help:
021-09-24 13:27:59.445 UTC [orderer.common.server] loadLocalMSP -> PANI 004 Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory
panic: Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory

**Comment by vanitas92** [comment]
Can you make sure that after executing the fabricOps.sh script, the crypto-config folder is populated with the certificates? Seems like they have not been created or the folder pointing in hostpath in the orderer deployment yaml do not point correctly in the local machine where the certificates should be.

**Comment by nkaramolegos** [comment]
I can see that the folder and files exist.  For example: 
_ls fabric-external-chaincodes/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls/_ gives me
**ca.crt  server.crt  server.key**

The fabric-external-chainocode is downloaded in my user home folder i.e /home/nick/fabric-external-chainocode. In this directory I run ./fabricOps.sh start (after chmod to 744)

Afterwards, I run: mkdir /home/nick/storage
I have replaced  in the entire directory's files the path: 
_/home/fabric-external-chaincodes/*_
with
_path: /home/nick/fabric-external-chaincodes/*_
Because in linux the absoulete paths have the structure /home/<$USER>/

However, the error (status error and the crashloopbackoff) remains after replacing the paths.

**Comment by nkaramolegos** [comment]
Do you take a look on that? I really need help.

**Comment by hujw** [comment]
@nkaramolegos I meet the same situation. May I know whether you use the minikube as your environment? If yes, you may create pods command in "minikube node" instead of your host machine. You can go into minikube node by using "minikube ssh" command. Hope this helps!

**Comment by khushalkunjir** [comment]
I am also facing same issue without minikube,
Can you please help?
Do we need to create pvc by own, meaning create pvc with those names which are specified into yaml files,
Because when i am doing kubectl get pvc -n hyperledger, no resource found coming 
Can you please help?
THank you in adavance

**Comment by khushalSnapper** [comment]
Hi Everyone,

I resolve the issue. The issue coming because the directory that i provided that was  /home/usename/storage, but when pod container accessing this directory he is not able to find. So i created this directory inside the root like /fabric/storage
mkdir -p /fabric/storage
after giving this directory inside the hostPath this issue will resolved. Also please read write access to this folder
