### ISSUE TITLE
bug on msp

### ISSUE THREAD

**Issue by zhangfuli** [vanitas92/fabric-external-chaincodes#2]
hello, I have successfully created all the crypto materials, and the **hostPath** is correct， but i got the following bug:
```
2020-05-02 15:24:50.192 UTC [orderer.common.server] loadLocalMSP -> PANI 0db Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory
```
I have no idea about this，Can you give me some guidance？thx

**Comment by zhangfuli** [comment]
I am a three-node network, pod is deployed on other nodes, so the generated certificate information cannot be found

**Comment by xoco70** [comment]
I have the same issue, but I deployed in on minikube with docker driver.

**Comment by moolkothari** [comment]
I am facing same issue, I have deployed this on minikube and I have mounted folder manually each command in seperate terminal

eg: 
minikube mount /home/storage/orderer:/var/hyperledger/production
minikube mount /home/fabric-external-chaincodes/channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
minikube mount /home/fabric-external-chaincodes/crypto-config/ordererOrganizations/consortium/orderers/orderer0/msp:/var/hyperledger/orderer/msp
minikube mount /home/fabric-external-chaincodes/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls:/var/hyperledger/orderer/tls
.................................. 
........................


still I am getting this error, I have attached the complete log  of orderer0 in the file as well. 

2021-01-17 08:00:21.894 UTC [orderer.common.server] loadLocalMSP -> PANI 0dd Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory
panic: Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory
[order0-log.txt](https://github.com/vanitas92/fabric-external-chaincodes/files/5825733/order0-log.txt)
