### ISSUE TITLE
PANI 0dd Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts

### ISSUE THREAD

**Issue by xoco70** [vanitas92/fabric-external-chaincodes#8]
Yep, same issue here too. Config : 
Minikube 1.16 with docker driver
host : ubuntu 20.04

`
	Metrics.Statsd.Network = "udp"	Metrics.Statsd.Address = "127.0.0.1:8125"	Metrics.Statsd.WriteInterval = 30s	Metrics.Statsd.Prefix = ""	ChannelParticipation.Enabled = false	ChannelParticipation.RemoveStorage = false2020-12-29 15:20:53.618 UTC [bccsp] GetDefault -> DEBU 0d8 Before using BCCSP, please call InitFactories(). Falling back to bootBCCSP.2020-12-29 15:20:53.618 UTC [bccsp_sw] createKeyStore -> DEBU 0d9 Creating KeyStore at [/var/hyperledger/orderer/msp/keystore]...2020-12-29 15:20:53.618 UTC [bccsp_sw] createKeyStore -> DEBU 0da KeyStore created at [/var/hyperledger/orderer/msp/keystore].2020-12-29 15:20:53.618 UTC [bccsp_sw] openKeyStore -> DEBU 0db KeyStore opened at [/var/hyperledger/orderer/msp/keystore]...done2020-12-29 15:20:53.618 UTC [msp] getPemMaterialFromDir -> DEBU 0dc Reading directory /var/hyperledger/orderer/msp/signcerts2020-12-29 15:20:53.618 UTC [orderer.common.server] loadLocalMSP -> PANI 0dd Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directorypanic: Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directorygoroutine 1 [running]:go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000428000, 0x0, 0x0, 0x0)	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:230 +0x545go.uber.org/zap.(*SugaredLogger).log(0xc00011e218, 0x4, 0x101e170, 0x22, 0xc0001594a8, 0x1, 0x1, 0x0, 0x0, 0x0)	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0x100go.uber.org/zap.(*SugaredLogger).Panicf(...)	/go/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panicf(...)	/go/src/github.com/hyperledger/fabric/common/flogging/zap.go:74github.com/hyperledger/fabric/orderer/common/server.loadLocalMSP(0xc00019e000, 0xc0001ac050, 0x0)	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:668 +0x10bgithub.com/hyperledger/fabric/orderer/common/server.Main()	/go/src/github.com/hyperledger/fabric/orderer/common/server/main.go:91 +0x252main.main()	/go/src/github.com/hyperledger/fabric/cmd/orderer/main.go:15 +0x20
`

I moved the repo folder to  `/home/julien/fabric-external-chaincodes`, the storage in `/home/julien/storage` and updated all refs in code.

I ran succesfully `./fabricOps.sh start`, and I have my cryptomaterial in: 

`/home/julien/fabric-external-chaincodes/crypto-config/ordererOrganizations/consortium/orderers/orderer0/msp/signcerts/orderer0-cert.pem`

which is coherent with yaml :

```
- name: orderer-claim1
          hostPath:
            path: /home/julien/fabric-external-chaincodes/crypto-config/ordererOrganizations/consortium/orderers/orderer0/msp
```

So it should have a: 

`/var/hyperledger/orderer/msp/signcerts/orderer0-cert.pem`

I notice there is no volumes created like `orderer1-persistentdata`, and directory `/home/julien/storage/orderer0` has not been created

**Comment by PierrickLozach** [comment]
Hi @xoco70 , have you found out what was wrong?

**Comment by xoco70** [comment]
Nop

**Comment by vanitas92** [comment]
Hi guys,

Sorry for the delay. I cannot offer support on minikube as i have no experience, but please make sure that the certificates files are in the pods, like create a simple pod like busybox mapping the same hostpath and see if the files are on the expected path. Please also check that the folder on the host has enough permissions for root user, like 744 permissions.

Thank you!

**Comment by tasoskalogero** [comment]
@xoco70 How do you start minikube?

I think minikube need sto mount a host directory in order to work with this project.

Let's say you cloned the project in the directory `/home/myusername/`

Then, start minikube like this:  `minikube start --mount-string /home/myusername:/host  --mount`

And in the k8s config files replace `/home/` with `/host/`

e.g. `path: /host/storage/orderer1` --> `path: /home/storage/orderer1`

**Comment by cdesch** [comment]
@tasoskalogero Do you do this with Docker for Windows?

**Comment by vanitas92** [comment]
Closing issue as no updates and out of scope problem.
