### ISSUE TITLE
Orderers Pods are not creating, status CrashLoopBackOff

### ISSUE THREAD

**Issue by moolkothari** [vanitas92/fabric-external-chaincodes#9]
I am trying to run this using minikube and I have mounted folder manually each command in seperate terminal as I read that in minikube we have to mount all the volumes 

eg:

minikube mount /home/storage/orderer:/var/hyperledger/production
minikube mount /home/fabric-external-chaincodes/channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
minikube mount /home/fabric-external-chaincodes/crypto-config/ordererOrganizations/consortium/orderers/orderer0/msp:/var/hyperledger/orderer/msp
minikube mount /home/fabric-external-chaincodes/crypto-config/ordererOrganizations/consortium/orderers/orderer0/tls:/var/hyperledger/orderer/tls
..................................
........................

still I am getting this error, I have attached the complete log of orderer0 in the file as well.
[order0-log.txt](https://github.com/vanitas92/fabric-external-chaincodes/files/5825735/order0-log.txt)

2021-01-17 08:00:21.894 UTC [orderer.common.server] loadLocalMSP -> PANI 0dd Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory
panic: Failed to get local msp config: could not load a valid signer certificate from directory /var/hyperledger/orderer/msp/signcerts: stat /var/hyperledger/orderer/msp/signcerts: no such file or directory

**Comment by vanitas92** [comment]
Closing it as we discussed on Linkedin if no new updates are required

**Comment by moolkothari** [comment]
I have created NFS server to for storage , crypto material and channel artifacts to deployee ordering nodes and other pods, one more issue I have face that docker images needs to be pushed to dockerhub, last issue was for generating genesis block I need to change the channel name instead of mychannel, anyway after spending lot of time, I was able to run the network now everything is working perfectly fine for me, any thanks for putting this stuff.
